"""
tests/test_claim_c_homogeneity.py — CLAIM-C's homogeneity calibration curve.

`POPPER_PLAN.md` §6f measured the two ends of CLAIM-C's one real limitation --
the prompts are not independent observations -- and left everything between
them uncontrolled. A real run lands in the middle. §6g closes that by measuring
the whole curve offline and having the gate report what its p corresponds to at
the homogeneity it observed.

Three things have to be true for that to be an improvement rather than a second
number to argue about, and this module is organised around them.

**The simulator must be the same test as the gate.** The curve is generated by
a second implementation of the gate's arithmetic -- a fast one, because the
honest version needs hundreds of thousands of draws. A second implementation is
a real risk, so `TestFastPathMatchesTheGate` pins it against `p_value_claim_c`
itself. If those two ever disagree, every number in the stored curve is a rate
of some other test and the correction is worse than nothing.

**The correction must actually restore calibration, and not only on the family
it was fitted to.** `TestCalibrationIsRestored` measures both. The
out-of-sample arm is the one that matters: `sign_homogeneity` is a scalar
summary, and a scalar cannot determine a distribution, so the question is
whether indexing by it transfers to a dependence mechanism the curve never saw.

**It must never buy power.** The exhaustive enumeration is genuinely
conservative at the independent end. `TestTheCorrectionNeverSharpens` pins that
the correction can only blunt.
"""

from __future__ import annotations

import json

import numpy as np
import pytest

# Tier: pure -- passes with torch, transformers, scikit-learn and matplotlib
# all unimportable.
pytestmark = pytest.mark.pure

from p1_mstate_tracking.replication_gate import (
    CLAIM_C_ALTERNATIVE,
    CLAIM_C_METRICS,
    CLAIM_C_RECIPROCAL_ALTERNATIVE,
    HOMOGENEITY_CURVE_SCHEMA_VERSION,
    _metric_subsets,
    apply_homogeneity_correction,
    adjudicate_claim_c,
    homogeneity_correction,
    load_homogeneity_curve,
    p_value_claim_c,
    rejection_rate_at,
)
from tools.calibrate_claim_c_homogeneity import (
    CURVE_PATH,
    SubsetPTable,
    _configs,
    best_attainable_p,
    check_curve,
    simulate_config,
)

M = len(CLAIM_C_METRICS)
REF_LAYERS, CAN_LAYERS = 36, 24
ALPHA = 0.05
SUBSETS = _metric_subsets()


# ---------------------------------------------------------------------------
# Fixtures: arms whose per-cell contrast SIGNS are exactly what we ask for
# ---------------------------------------------------------------------------

def _prompts(n):
    return [f"prompt_{i}" for i in range(n)]


def _arm(deltas, prompts, n_layers):
    return {p: {m: [float(deltas[i, j])] * n_layers
                for j, m in enumerate(CLAIM_C_METRICS)}
            for i, p in enumerate(prompts)}


def _four_arms(ref_signs, can_signs, prompts):
    n_p = len(prompts)
    zeros_ref = _arm(np.zeros((n_p, M)), prompts, REF_LAYERS)
    zeros_can = _arm(np.zeros((n_p, M)), prompts, CAN_LAYERS)
    return (_arm(ref_signs, prompts, REF_LAYERS), zeros_ref,
            _arm(can_signs, prompts, CAN_LAYERS), zeros_can)


def _step0(prompts):
    return _arm(np.full((len(prompts), M), 0.25), prompts, CAN_LAYERS)


def _gate(ref_signs, can_signs, prompts):
    rt, rr, ct, cr = _four_arms(ref_signs, can_signs, prompts)
    return p_value_claim_c(rt, rr, ct, cr, candidate_step0=_step0(prompts))


def _heterogeneous(n, seed=11):
    rng = np.random.default_rng(seed)
    while True:
        s = rng.choice([-1.0, 1.0], size=(n, M))
        if len({tuple(r) for r in s.tolist()}) > 1:
            return s


def _consistent_but_not_degenerate(n=8):
    """
    A candidate table with high `sign_homogeneity` and no degenerate subset.

    Every metric column has a single dissenting prompt, and a DIFFERENT one
    each time, so each column is 7/8 unanimous (homogeneity 0.875) while no two
    prompts carry the same sign row and no leave-one-out subset collapses. That
    separation matters: it is the only way to exercise the homogeneity refusal
    without simultaneously tripping the identical-rows one.
    """
    s = np.ones((n, M))
    for j in range(M):
        s[j % n, j] = -1.0
    return s


# ---------------------------------------------------------------------------
# The simulator IS the gate
# ---------------------------------------------------------------------------

class TestFastPathMatchesTheGate:
    """
    The curve is only meaningful if the thing that generated it computes the
    same p the gate does. Everything else in this file rests on this class.
    """

    @pytest.mark.parametrize("n_prompts", [6, 7, 8])
    def test_p_values_agree_exactly_on_random_tables(self, n_prompts):
        tables = {len(c): SubsetPTable(n_prompts, len(c)) for _, c in SUBSETS}
        rng = np.random.default_rng(4242)
        prompts = _prompts(n_prompts)
        compared = 0
        for _ in range(20):
            ref = rng.choice([-1.0, 1.0], size=M)
            can = rng.choice([-1.0, 1.0], size=(n_prompts, M))
            res = _gate(np.tile(ref, (n_prompts, 1)), can, prompts)

            conc = can == ref[None, :]
            fast_g = fast_l = 0.0
            for _, cols in SUBSETS:
                sub = conc[:, list(cols)]
                a, b = tables[len(cols)].lookup(sub.sum(axis=1)[None, :])
                fast_g, fast_l = max(fast_g, a[0]), max(fast_l, b[0])

            if res.get("p_value_uncorrected") is None:
                continue                       # a refusal; nothing to compare
            assert res["p_value_uncorrected"] == pytest.approx(fast_g, abs=1e-12)
            assert res["p_reciprocal_uncorrected"] == pytest.approx(fast_l, abs=1e-12)
            compared += 1
        assert compared >= 10, "fixture drifted into refusing almost everything"

    def test_the_exhaustive_table_reproduces_the_attainable_floor(self):
        """
        The smallest p a subset table can express is 2/(2^n + 1) -- the same
        number the gate's own attainable-floor refusal is derived from.
        """
        for n in (6, 8):
            t = SubsetPTable(n, M)
            assert t.p_greater.min() == pytest.approx(best_attainable_p(n))
            assert t.p_less.min() == pytest.approx(best_attainable_p(n))


# ---------------------------------------------------------------------------
# The stored curve describes the gate that reads it
# ---------------------------------------------------------------------------

class TestCurveIsInStepWithTheGate:

    def test_committed_curve_is_not_stale(self):
        problems = check_curve(CURVE_PATH)
        assert problems == [], (
            "the committed curve no longer describes the current gate; "
            "regenerate with tools/calibrate_claim_c_homogeneity.py --write")

    def test_curve_records_what_it_measured(self):
        c = load_homogeneity_curve()
        assert c["schema_version"] == HOMOGENEITY_CURVE_SCHEMA_VERSION
        assert c["metrics"] == list(CLAIM_C_METRICS)
        assert c["alternative"] == CLAIM_C_ALTERNATIVE
        assert c["reciprocal_alternative"] == CLAIM_C_RECIPROCAL_ALTERNATIVE
        assert c["subset_names"] == [n for n, _ in SUBSETS]
        # The two things a reader must not have to infer: which H0 family the
        # rates are rates under, and that they are conditional on emission.
        assert "per-metric shared sign propensity" in c["_h0_family"]
        assert "conditional on the gate EMITTING" in c["_conditioning"]
        assert c["assumes_complete_table"] is True

    def test_quantile_rows_are_monotone_in_level(self):
        c = load_homogeneity_curve()
        for row in c["curves"].values():
            for b in row["bins"]:
                for key in ("quantiles_greater", "quantiles_less"):
                    q = b[key]
                    if q is None:
                        continue
                    assert list(q) == sorted(q), (
                        f"{key} is not a quantile function in bin {b['lo']}")

    def test_the_degenerate_top_bin_has_no_measurement(self):
        """
        Under H0 at homogeneity above 0.975 essentially every draw hits the
        identical-rows refusal, so there is no emitted distribution to
        calibrate against. The curve says so rather than extrapolating, and the
        gate refuses there.
        """
        c = load_homogeneity_curve()
        top = c["curves"]["8"]["bins"][-1]
        assert top["quantiles_greater"] is None
        assert not top["measured"]


# ---------------------------------------------------------------------------
# The correction blunts and never sharpens
# ---------------------------------------------------------------------------

class TestTheCorrectionNeverSharpens:
    """
    The chosen rule is max(p_exact, R(h, p_exact)).

    Taking R unconditionally would be defensible on power grounds -- at the
    independent end the enumeration is conservative by a factor of ten and
    calibrating would recover it -- but it trades an EXACT conditional
    guarantee for a simulated one, on the one claim carrying a hard stop.
    """

    def test_the_reported_p_is_never_below_the_exact_one(self):
        """
        Swept across the homogeneity range, so the fixture covers both the
        regime where the correction does nothing and the regime where it
        binds. Candidate rows are drawn with a per-metric shared propensity --
        the curve's own H0 family -- because that is what moves homogeneity;
        correlating the candidate with the REFERENCE instead moves the
        statistic and leaves homogeneity near 0.64 throughout.
        """
        rng = np.random.default_rng(5)
        seen_equal = seen_blunted = 0
        for n in (7, 8):
            prompts = _prompts(n)
            for b in (0.0, 0.1, 0.2, 0.25, 0.3, 0.35):
                for _ in range(3):
                    ref = rng.choice([-1.0, 1.0], size=(n, M))
                    q = 0.5 + rng.choice([-1.0, 1.0], size=M) * b
                    can = np.where(rng.random((n, M)) < q, 1.0, -1.0)
                    r = _gate(ref, can, prompts)
                    if r.get("p_value") is None:
                        continue
                    assert r["p_value"] >= r["p_value_uncorrected"] - 1e-12
                    assert (r["p_reciprocal"]
                            >= r["p_reciprocal_uncorrected"] - 1e-12)
                    if r["p_value"] > r["p_value_uncorrected"]:
                        seen_blunted += 1
                    else:
                        seen_equal += 1
        assert seen_equal and seen_blunted, (
            f"the fixture should cover both the no-op and the blunting case; "
            f"got equal={seen_equal} blunted={seen_blunted}")

    def test_it_is_a_no_op_where_the_enumeration_is_already_conservative(self):
        """
        Eight prompts whose sign rows disagree as much as coin flips sit near
        homogeneity 0.64, where the measured H0 rate at alpha is far BELOW
        alpha. The correction has nothing to do there, and a perfect transfer
        still clears.
        """
        prompts = _prompts(8)
        ref = _heterogeneous(8)
        r = _gate(ref, ref.copy(), prompts)
        assert r["sign_homogeneity"] < 0.7
        assert r["p_value"] == pytest.approx(r["p_value_uncorrected"])
        assert r["homogeneity_corrected"] is False
        assert r["verdict"] == "TRANSFERS"

    def test_it_can_take_a_verdict_away_and_that_is_the_whole_point(self):
        """
        The substantive consequence, pinned rather than left implicit.

        This table clears at alpha on the exact enumeration (p = 0.031) and
        does not clear once corrected (0.105), because its prompts agree with
        each other far more than independent rows would --
        `sign_homogeneity` 0.8125, where the measured H0 rejection rate at
        alpha is roughly twice alpha. Before the curve existed this run
        reported TRANSFERS and the sweep proceeded; it now reports
        INSUFFICIENT, which stops the sweep without recording a falsification.

        That is the correction costing a verdict, which is what a correction
        that only ever blunts is FOR. A test suite in which the correction
        never changed an outcome would not be evidence that it works.
        """
        prompts = _prompts(8)
        ref = np.array([
            [-1, 1, -1, -1, -1, 1], [1, -1, 1, -1, 1, -1],
            [-1, 1, -1, -1, 1, -1], [1, 1, -1, -1, 1, 1],
            [1, -1, 1, -1, 1, 1], [1, -1, -1, -1, 1, -1],
            [-1, -1, -1, -1, 1, 1], [1, -1, -1, -1, 1, 1]], dtype=float)
        can = np.array([
            [1, 1, -1, -1, -1, 1], [1, -1, 1, -1, 1, -1],
            [1, -1, 1, -1, 1, -1], [1, -1, -1, -1, 1, -1],
            [1, -1, 1, 1, -1, -1], [1, 1, 1, -1, 1, -1],
            [1, -1, 1, -1, 1, 1], [1, -1, 1, -1, 1, -1]], dtype=float)

        r = _gate(ref, can, prompts)
        assert r["sign_homogeneity"] == pytest.approx(0.8125)
        assert r["p_value_uncorrected"] <= ALPHA < r["p_value"]
        assert r["homogeneity_corrected"] is True
        assert r["verdict"] == "INSUFFICIENT"
        assert r["hard_stop"] is True
        # Insufficient is not falsified: an e-process records "not shown",
        # never "null accepted".
        assert r["falsified"] is False

    def test_the_reciprocal_direction_is_corrected_too(self):
        """
        FAILS-TO-TRANSFER is the branch that writes a falsification into the
        ledger. Correcting only the adjudicated direction would leave the
        falsifying one running at the inflated rate -- which is the worse of
        the two to get wrong.
        """
        corr = homogeneity_correction(8, 0.79)
        assert corr["available"]
        floor = best_attainable_p(8)
        assert apply_homogeneity_correction(
            corr, floor, CLAIM_C_RECIPROCAL_ALTERNATIVE) > floor


class TestReaderIsConservative:

    def test_rounds_up_to_the_next_tabulated_level(self):
        levels = [0.01, 0.05, 0.2]
        quantiles = [0.001, 0.010, 0.100]
        # Two levels sit at or below p=0.05, so the honest rate is the next
        # level up rather than the largest one that fits.
        assert rejection_rate_at(levels, quantiles, 0.05) == 0.2

    def test_a_p_below_every_quantile_reads_as_the_resolution_floor(self):
        """
        Not zero. The simulation cannot certify a rate it never had the draws
        to see, and reporting zero would claim the correction is unnecessary
        precisely where the measurement ran out.
        """
        assert rejection_rate_at([0.01, 0.05], [0.5, 0.9], 0.001) == 0.01

    def test_a_p_above_every_quantile_is_certain(self):
        assert rejection_rate_at([0.01, 0.05], [0.001, 0.002], 0.9) == 1.0


# ---------------------------------------------------------------------------
# The payoff: is the Type-I rate actually restored?
# ---------------------------------------------------------------------------

def _score(tables, table):
    """(homogeneity, emitted, p_greater) for a batch of concordance tables."""
    f = table.mean(axis=1)
    hom = np.maximum(f, 1.0 - f).mean(axis=1)
    refused = np.zeros(len(table), dtype=bool)
    pg = np.zeros(len(table))
    for _, cols in SUBSETS:
        sub = table[:, :, list(cols)]
        refused |= (sub == sub[:, :1, :]).all(axis=(1, 2))
        pg = np.maximum(pg, tables[len(cols)].lookup(sub.sum(axis=2))[0])
    return hom, ~refused, pg


def _corrected_rate(n_prompts, hom, emitted, pg, alpha=ALPHA):
    """The corrected gate's rejection rate among the draws it emits on."""
    floor = best_attainable_p(n_prompts)
    n_em = n_rej = 0
    for h, p, e in zip(hom, pg, emitted):
        if not e:
            continue
        corr = homogeneity_correction(n_prompts, float(h))
        if not corr["available"]:
            continue
        if apply_homogeneity_correction(corr, floor, CLAIM_C_ALTERNATIVE) > alpha:
            continue                            # the derived refusal
        n_em += 1
        n_rej += int(apply_homogeneity_correction(
            corr, float(p), CLAIM_C_ALTERNATIVE) <= alpha)
    return (n_rej / n_em if n_em else float("nan")), n_em


class TestCalibrationIsRestored:
    """
    The measurement the whole build exists to make. Draw counts are stated in
    each assertion's tolerance rather than implied: these are ~6000-draw rates,
    so a nominal 0.05 is resolved to about +/- 0.006.
    """

    N = 8

    def _tables(self):
        return {len(c): SubsetPTable(self.N, len(c)) for _, c in SUBSETS}

    def test_the_worst_fitted_configuration_comes_back_to_nominal(self):
        """
        In-sample, so this checks the machinery rather than its
        generalisation: the curve was fitted on this family. What it rules out
        is an error of implementation -- a bin misread, a direction swapped, a
        correction applied to the wrong number.
        """
        tables = self._tables()
        rng = np.random.default_rng(31337)
        worst_raw = worst_corrected = 0.0
        # The high-bias uniform configurations are where the inflation lives.
        for shape, b in [c for c in _configs(M) if c == ("uniform", 0.3)
                         or c == ("uniform", 0.35) or c == ("khot:5", 0.4)]:
            res = simulate_config(self.N, M, SUBSETS, tables, shape, b, 6000, rng)
            emitted = res["emitted"]
            if emitted.sum() < 500:
                continue
            worst_raw = max(worst_raw,
                            float((res["p_greater"][emitted] <= ALPHA).mean()))
            rate, n_em = _corrected_rate(
                self.N, res["homogeneity"], emitted, res["p_greater"])
            if n_em >= 500:
                worst_corrected = max(worst_corrected, rate)

        assert worst_raw > 2 * ALPHA, (
            "fixture no longer reaches the inflated regime it is meant to test")
        assert worst_corrected <= ALPHA + 0.01

    def test_it_holds_on_a_dependence_family_the_curve_never_saw(self):
        """
        The arm that matters. `sign_homogeneity` is a scalar summary and a
        scalar cannot determine a distribution, so the open question is whether
        indexing the correction by it transfers to a different MECHANISM of
        dependence.

        The out-of-sample family is the duplicate-prompt mixture: with
        probability rho a prompt's sign row is a copy of a shared consensus row
        rather than its own draw. That is "some prompts are redundant", where
        the fitted family is "some metrics are architecture-wide" -- the same
        homogeneity reached by an unrelated route.
        """
        tables = self._tables()
        rng = np.random.default_rng(20260824)
        results = {}
        for rho in (0.4, 0.6, 0.8):
            consensus = rng.random((8000, 1, M)) < 0.5
            own = rng.random((8000, self.N, M)) < 0.5
            take = rng.random((8000, self.N, 1)) < rho
            table = np.where(take, np.broadcast_to(consensus, own.shape), own)

            hom, emitted, pg = _score(tables, table)
            raw = float((pg[emitted] <= ALPHA).mean())
            corrected, n_em = _corrected_rate(self.N, hom, emitted, pg)
            results[rho] = (raw, corrected, n_em)

        # Uncorrected, this family inflates the way the fitted one does.
        assert results[0.8][0] > 2 * ALPHA
        for rho, (raw, corrected, n_em) in results.items():
            assert n_em >= 500, f"rho={rho} emitted too little to measure"
            assert corrected <= ALPHA + 0.01, (
                f"rho={rho}: corrected rate {corrected:.4f} exceeds nominal on a "
                f"family the curve was not fitted to")
            assert corrected < raw + 1e-9


# ---------------------------------------------------------------------------
# The refusal, and that it is derived rather than placed
# ---------------------------------------------------------------------------

class TestTheDerivedRefusal:
    """
    The second question this construction had to settle was whether there is a
    homogeneity above which the gate refuses instead of correcting. There is,
    and it is derived from alpha exactly as the attainable-floor refusal is:
    refuse where the measured rate at the design's BEST attainable p already
    exceeds alpha, because then no result whatsoever survives its own
    correction. No homogeneity constant appears anywhere in the module.
    """

    def test_high_homogeneity_refuses_rather_than_reporting_a_corrected_p(self):
        prompts = _prompts(8)
        can = _consistent_but_not_degenerate(8)
        r = _gate(can.copy(), can, prompts)
        assert r["sign_homogeneity"] == pytest.approx(0.875)
        assert r["p_value"] is None
        assert "would not survive its own correction" in r["reason"]
        assert r["verdict"] == "INSUFFICIENT"
        # Refusing is not falsifying: nothing was shown either way.
        assert r["falsified"] is False
        assert r["hard_stop"] is True

    def test_the_boundary_moves_with_alpha_because_it_is_derived_from_it(self, monkeypatch):
        """
        The distinguishing property of a derived cut over a placed one. A
        tolerance would sit at the same homogeneity whatever alpha is.
        """
        import p1_mstate_tracking.replication_gate as gate
        prompts = _prompts(8)
        can = _consistent_but_not_degenerate(8)

        monkeypatch.setattr(gate, "_alpha", lambda: 0.5)
        r = _gate(can.copy(), can, prompts)
        assert r["alpha"] == 0.5
        assert r["p_value"] is not None, (
            "the refusal did not move when alpha did, so it is a placed "
            "threshold rather than a derived one")

    def test_the_refusal_reports_what_it_measured(self):
        prompts = _prompts(8)
        r = _gate(_consistent_but_not_degenerate(8).copy(),
                  _consistent_but_not_degenerate(8), prompts)
        hc = r["homogeneity_correction"]
        assert hc["available"] is True
        assert hc["bin_lo"] <= r["sign_homogeneity"] <= hc["bin_hi"]
        assert hc["corrected_best_attainable_p"] > r["alpha"]
        # The quantile rows themselves stay out of the result: they are 55
        # numbers per direction and the record should say which bin was read,
        # not reproduce the table.
        assert "quantiles_greater" not in hc


class TestRefusesRatherThanFallingBackToTheUncorrectedP:
    """
    Once the correction is what enters the e-value, an uncorrected p reaching
    the ledger is not a degraded answer -- it is a Type-I guarantee asserted on
    a null already measured to be anticonservative. So every way of failing to
    get a correction is a refusal.
    """

    def _unreadable(self, tmp_path, payload=None):
        p = tmp_path / "curve.json"
        if payload is not None:
            p.write_text(json.dumps(payload))
        return p

    def test_a_missing_curve_refuses(self, tmp_path):
        corr = homogeneity_correction(8, 0.6, path=tmp_path / "absent.json")
        assert corr["available"] is False
        assert "could not be read" in corr["reason"]

    def test_a_curve_at_another_schema_version_refuses(self, tmp_path):
        p = self._unreadable(tmp_path, {"schema_version": 999})
        corr = homogeneity_correction(8, 0.6, path=p)
        assert corr["available"] is False
        assert "schema_version" in corr["reason"]

    def test_a_curve_measured_on_other_metrics_refuses(self, tmp_path):
        p = self._unreadable(tmp_path, {
            "schema_version": HOMOGENEITY_CURVE_SCHEMA_VERSION,
            "metrics": ["only_one_metric"]})
        corr = homogeneity_correction(8, 0.6, path=p)
        assert corr["available"] is False
        assert "different metric set" in corr["reason"]

    def test_an_untabulated_prompt_count_refuses(self):
        corr = homogeneity_correction(40, 0.6)
        assert corr["available"] is False
        assert "no calibration curve is tabulated" in corr["reason"]

    def test_the_gate_refuses_and_does_not_quietly_report_the_exact_p(self, tmp_path):
        import p1_mstate_tracking.replication_gate as gate
        prompts = _prompts(8)
        ref = _heterogeneous(8)
        monkey = tmp_path / "absent.json"
        old = gate.HOMOGENEITY_CURVE_PATH
        try:
            gate.HOMOGENEITY_CURVE_PATH = monkey
            r = _gate(ref, ref.copy(), prompts)
        finally:
            gate.HOMOGENEITY_CURVE_PATH = old
        assert r["p_value"] is None
        assert "the correction is what enters the e-value" in r["reason"]
        assert r["hard_stop"] is True


# ---------------------------------------------------------------------------
# What reaches the ledger
# ---------------------------------------------------------------------------

class TestTheRecordSaysWhatWasCorrected:

    def test_the_note_carries_both_p_values_and_the_bin(self, tmp_path):
        prompts = _prompts(8)
        ref = _heterogeneous(8)
        rt, rr, ct, cr = _four_arms(ref, ref.copy(), prompts)
        res = adjudicate_claim_c(rt, rr, ct, cr, candidate_step0=_step0(prompts),
                                 adjudicate=True, adjudications_dir=tmp_path)
        assert res["adjudication"] is not None
        rec = json.loads((tmp_path / "CLAIM-C.json").read_text())
        notes = rec["notes"]
        assert "homogeneity_correction" in notes
        assert "p_uncorrected" in notes
        # The adjudicated number is the corrected one.
        assert rec["p_value"] == pytest.approx(res["p_value"])

    def test_the_ledger_is_untouched_without_the_flag(self, tmp_path):
        prompts = _prompts(8)
        ref = _heterogeneous(8)
        rt, rr, ct, cr = _four_arms(ref, ref.copy(), prompts)
        res = adjudicate_claim_c(rt, rr, ct, cr, candidate_step0=_step0(prompts),
                                 adjudications_dir=tmp_path)
        assert res["adjudication"] is None
        assert not list(tmp_path.iterdir())
