"""
tools/build_doc_index.py -- a line-range index of each large Markdown document.

Why: `PROJECT.md` is ~120k tokens and `POPPER_PLAN.md` ~70k. A session that
needs one section otherwise greps and then reads around the hits, or pages
through the file. The index gives every heading its start line, its length
and an approximate token cost, so the next step is one `Read` with
`offset`/`limit` (`LESSONS.md` lesson 9; `archive/docs/agent_context_scan_2026-09-22.md`).

Output: `docs/index/<STEM>.idx.md`, one per document in `DOCS`. Generated; do
not edit by hand. `--check` fails when a committed index is stale, so CI keeps
it in step with the document (`scripts/check.sh lint`).

Stdlib only: this runs in tier 0, where numpy is unimportable.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "docs" / "index"

# The documents too large to read whole. Add one here when it crosses ~40 KB
# and sessions start reading it for single sections.
DOCS = ["PROJECT.md", "POPPER_PLAN.md"]

_HEADING = re.compile(r"^(#{2,4}) (.+?)\s*$")
# Long sections are written as bold lettered paragraphs ("**A. ...**", "**F. ...**")
# rather than sub-headings. Inside a section longer than LONG_SECTION lines those
# become index rows too, one level below the section; elsewhere they are ignored.
_BOLD_HEAD = re.compile(r"^\*\*([A-Z]|\d{1,2})\. (.+?)(\*\*|$)")
LONG_SECTION = 300
_FENCE = re.compile(r"^(```|~~~)")
MAX_TITLE = 140
BYTES_PER_TOKEN = 4  # rough for English prose; code-dense text runs higher


def sections(text: str) -> list[tuple[int, int, int, int, str]]:
    """(level, start_line, n_lines, n_bytes, title) per heading, 1-based lines.

    A section runs to the next heading of any indexed level, so the ranges
    tile the document from the first heading on. Headings inside fenced code
    blocks are not headings.
    """
    lines = text.splitlines(keepends=True)
    heads: list[tuple[int, int, str]] = []
    bold: list[tuple[int, str]] = []
    in_fence = False
    for i, line in enumerate(lines):
        if _FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = _HEADING.match(line.rstrip("\n"))
        if m:
            heads.append((len(m.group(1)), i, m.group(2)))
            continue
        b = _BOLD_HEAD.match(line)
        if b:
            bold.append((i, f"**{b.group(1)}.** {b.group(2).rstrip('*').strip()}"))
    ends = [heads[k + 1][1] if k + 1 < len(heads) else len(lines) for k in range(len(heads))]
    extra = []
    for (level, start, _), end in zip(heads, ends):
        if end - start > LONG_SECTION:
            extra += [(level + 1, i, t) for i, t in bold if start < i < end]
    heads = sorted(heads + extra, key=lambda h: h[1])
    out = []
    for k, (level, start, title) in enumerate(heads):
        end = heads[k + 1][1] if k + 1 < len(heads) else len(lines)
        n_bytes = sum(len(l.encode("utf-8")) for l in lines[start:end])
        out.append((level, start + 1, end - start, n_bytes, title))
    return out


def render(doc: str, text: str) -> str:
    secs = sections(text)
    total = len(text.encode("utf-8"))
    n_lines = len(text.splitlines())
    w = [
        f"# Index of `{doc}`",
        "",
        f"Generated by `tools/build_doc_index.py`; do not edit. `{doc}`: "
        f"{n_lines} lines, ~{total // BYTES_PER_TOKEN // 1000}k tokens (bytes/4).",
        "Read one section: `Read` with `offset` = start, `limit` = lines.",
        "Indent marks depth: none = `##`, `·` = `###`, `··` = `####`; a bold "
        f"**A.** row is a lettered paragraph inside a section over {LONG_SECTION} lines.",
        "",
        "| start | lines | ~tok | section |",
        "|---:|---:|---:|---|",
    ]
    for level, start, n, n_bytes, title in secs:
        title = title.replace("|", "\\|")
        if len(title) > MAX_TITLE:
            title = title[: MAX_TITLE - 1] + "…"
        indent = "·" * (level - 2)
        tok = n_bytes // BYTES_PER_TOKEN
        tok_s = f"{tok / 1000:.1f}k" if tok >= 1000 else str(tok)
        w.append(f"| {start} | {n} | {tok_s} | {indent}{' ' if indent else ''}{title} |")
    return "\n".join(w) + "\n"


def index_path(doc: str) -> Path:
    return OUT_DIR / f"{Path(doc).stem}.idx.md"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any committed index differs from a fresh render")
    args = ap.parse_args(argv)
    stale = []
    for doc in DOCS:
        src = ROOT / doc
        fresh = render(doc, src.read_text(encoding="utf-8"))
        out = index_path(doc)
        if args.check:
            if not out.is_file() or out.read_text(encoding="utf-8") != fresh:
                stale.append(out.relative_to(ROOT))
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(fresh, encoding="utf-8")
            print(f"wrote {out.relative_to(ROOT)}")
    if stale:
        for p in stale:
            print(f"STALE: {p} -- run `python3 tools/build_doc_index.py`", file=sys.stderr)
        return 1
    if args.check:
        print(f"doc indexes in step ({', '.join(DOCS)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
